### ISSUE TITLE
Rename some apps

### ISSUE THREAD

**Issue by fabien-roy** [treeview-app/treeview#108]
Instead of @treeview, call things @acme/something.

Remove all references of "TreeView" to "ACME" and "treeview" to "acme" or "@acme" accordingly.

Rename "trpc" for "api"
Rename "database" for "db"

Place packages into folders:

- api
- db
- config
- mobile
- web

## Attack plan

PR #120 will be abandonned. It doesn't work and it's 300+ files. Nice POC tho.

I'll reuse that PR for the following, one PR at the time. Each PR will contain code, docs, workflow and config changes scoped to a single app or package.

You got this.

- [x] `apps/web` -> #121
- [x] `apps/mobile` -> #122
- [x] `apps/mobile-storybook` -> 141
- [x] `packages/db` -> #128
- [x] `packages/api` -> #129
- [x] `packages/theme` -> #130
- [x] `packages/config/tsconfig` -> #133
- [x] `packages/config/eslint` -> #132
- [x] `packages/config/stylelint` -> #131
- [x] `packages/web/ui` -> #140 (kinda, but we'll need a new issue)
- [x] `packages/web/forms` -> #137
- [x] `packages/web/locales` -> #136
- [x] `packages/web/storage` -> #135
- [x] `packages/mobile/ui` -> #123
- [x] `packages/mobile/forms` -> #126 
- [x] `packages/mobile/locales` -> #127 
- [x] `packages/mobile/storage` -> #124
